version: '3'
services:
  web:
    image: cobiro/php-nginx:latest
    volumes:
      - .:/var/www/cobiro
    ports:
      - "85:80"
  php:
    image: cobiro/php-xdebug:latest
    volumes:
      - .:/var/www/cobiro
  db:
    image: mariadb
    environment:
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_DATABASE: '${DB_DATABASE}'
